Console.Clear();
System.Console.Write("Enter meaning x1: ");
double x1 = double.Parse(Console.ReadLine());
System.Console.Write("Enter meaning y1: ");
double y1 = double.Parse(Console.ReadLine());
System.Console.Write("Enter meaning z1: ");
double z1 = double.Parse(Console.ReadLine());
System.Console.Write("Enter meaning x2: ");
double x2 = double.Parse(Console.ReadLine());
System.Console.Write("Enter meaning y2: ");
double y2 = double.Parse(Console.ReadLine());
System.Console.Write("Enter meaning z2: ");
double z2 = double.Parse(Console.ReadLine());
double vector = Math.Sqrt(Math.Pow((x2 - x1), 2) + Math.Pow((y2 - y1), 2) + Math.Pow((z2 - z1), 2));
System.Console.WriteLine(vector);